language: python
python: 
  - '3.8'
  - '3.7'
  - '3.6'
cache: pip
before_install:
  - python --version
  - python -m pip install --upgrade pip
  - pip install black pytest pytest-xdist
install:
  - pip install -e .
script:
  - black . --check
  - echo "import textattack" | python # run textattack post-install hooks
  - travis_wait 30 pytest tests -vx --dist=loadfile -n auto
