language: python
python: '3.8'
cache: pip
before_install:
  - python --version
  - python -m pip install --upgrade pip
  - pip install black pytest pytest-xdist
install:
  - pip install -e .
script:
  - black . --check
  - pytest tests -vx --dist=loadfile -n auto
